# Generated by Django 4.0.1 on 2022-02-10 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_minesweeperscore_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='minesweeperscore',
            old_name='user',
            new_name='owner',
        ),
    ]
